name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go version

      - name: Cache
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - uses: actions/checkout@v2
      - run: go build -v ./...

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test
      - uses: actions/checkout@v2
      - run: go test -v ./...
